### ISSUE TITLE
1.19.2 Forge Support

### ISSUE THREAD

**Issue by Aiidoneus** [caunt/BungeeForge#1]
Hello,
Is there anyway you can support 1.19.2 forge support? This is required for several Feed-The-Beast modpacks like Direwolf20 1.19.2 and FTB Legends of the Eye. My network would appreciate this. 

Thanks in advance!

**Comment by caunt** [comment]
I've released the 1.19.2 version and tested it with Direwolf20 modpack you mentioned. Let me know if there anything I can help you with.
[Release](https://github.com/caunt/BungeeForge/releases/tag/v1.0.5)

**Comment by Aiidoneus** [comment]
Thank you for doing this. I will be looking at testing this in the next couple of days.
