### ISSUE TITLE
How to connect with origin bungee

### ISSUE THREAD

**Issue by rong-xiaoli** [caunt/BungeeForge#10]
I'm running 1.16.5 forge and a origin bungee and I guess I need Ambassador to run but it is a Velocity plugin. What I know is that Velocity plugins won't work with bungeecord, so am I going to use Ambassador or something else?
Thanks!

**Comment by caunt** [comment]
I don't know much about bungeecord working with modern forge, but your guess is right. Ambassador does the main thing to allow modern forge behind the proxy. If it's possible for you, you can migrate to Velocity and use these plugins. If not, you should look for Ambassador alternatives on BungeeCord. It's possible to develop same functionality on both platforms.

When you're ready with modded connections and modern forge is working fine, only then you can try BungeeForge or Proxy Compatible Forge mods to support player data forwarding.

**Comment by rong-xiaoli** [comment]
Thanks. Problem solved.

**Comment by mckzstudios** [comment]
Why have Bungee in your name if you dont support Bungeecord.
