### ISSUE TITLE
1.6.4 + 1.5.2 support

### ISSUE THREAD

**Issue by yesBad** [caunt/BungeeForge#13]
If these could be done that'd be appreciated!

Also is there anyway to get ipforwarding working aka the client server would show correct ip for the joint player instead or showing proxy ip? (legacy auth)

Thank you, btw is there a way to donate?

**Comment by caunt** [comment]
Hi 👋 appreciate for donations if you want to, I added info [here](https://github.com/caunt/BungeeForge)
I will make 1.5.2 and 1.6.4 release this or next day. IP forwarding should already work. Does it still show you IP of the proxy?

**Comment by yesBad** [comment]
> Hi 👋 appreciate for donations if you want to, I added info [here](https://github.com/caunt/BungeeForge)

👍 
> I will make 1.5.2 and 1.6.4 release this or next day.

Will be fun to see & make work.
> IP forwarding should already work. Does it still show you IP of the proxy?

It does show my proxy IP in the Forge server, and yeah I'm not sure if I missed something or what's up...
I'm using Forge 1.12.2 2860, with Velocity 3.3.0.

**Comment by caunt** [comment]
> It does show my proxy IP in the Forge server, and yeah I'm not sure if I missed something or what's up... I'm using Forge 1.12.2 2860, with Velocity 3.3.0.

I will check it. What server software do you use? Simply forge?

**Comment by yesBad** [comment]
> I will check it. What server software do you use? Simply forge?

Yep just Forge 1.12.2 2860, I hate hybrids.

**Comment by caunt** [comment]
Just released [v1.0.6](https://github.com/caunt/BungeeForge/releases/tag/v1.0.6) with fix to forwarded IPs

I caught many errors while trying to setup 1.5.2/1.6.4 forge environments as this versions not supported even by community. To build 1.7.10 version previously I found solution, but for lower versions now it's practically impossible due to missing many repositories from mojangs and very outdated forge [src](https://files.minecraftforge.net/net/minecraftforge/forge/index_1.6.4.html). I will try again to setup them a bit later, but chances are low.

**Comment by yesBad** [comment]
Thanks for the fix (I'll try it soon!) and yeah... They're old versions nowdays, but some great mods with them. :) 
If you can get them to somehow be built then that'd be epic, but it's fine :p


EDIT; Fix works perfect! Thanks.

**Comment by yesBad** [comment]
> I caught many errors while trying to setup 1.5.2/1.6.4 forge environments as this versions not supported even by community. To build 1.7.10 version previously I found solution, but for lower versions now it's practically impossible due to missing many repositories from Mojangs and very outdated forge [src](https://files.minecraftforge.net/net/minecraftforge/forge/index_1.6.4.html). I will try again to setup them a bit later, but chances are low.

Any success? I could try & help with it as well, also if you'd like to add in Discord for example?


EDIT: It appears it would require more massive changes to get it to work as 1.7.2 below doesn't have uuids or netty from what I heard.. and getting 1.6.4 and below to build is a bit too much pain.

**Comment by caunt** [comment]
I've found community forge dev environment for versions below 1.7.2, will test it in near days

**Comment by yesBad** [comment]
> I've found community forge dev environment for versions below 1.7.2, will test it in near days

Goodluck... But yeah Velocity for example has no support for below 1.7.2...

**Comment by caunt** [comment]
> > I've found community forge dev environment for versions below 1.7.2, will test it in near days
> 
> Goodluck... But yeah Velocity for example has no support for below 1.7.2...

Then does that even worth effort to make this? 😅 does bungeecord support those versions?

I've found Voldeloom project to develop mods for this old versions.

**Comment by caunt** [comment]
I see it [does support](https://github.com/SpigotMC/BungeeCord/blob/edc5b4dc91cfacd753f12f553d9b2476a50a25e3/proxy/src/main/java/net/md_5/bungee/ServerConnector.java#L82) versions 1.6.4 and older. But only data it's forwarding, is incoming player IP and port. 

Do you really use this old versions bungeecord? If so, I can try to make bungeeforge for it.

**Comment by yesBad** [comment]
> Do you really use this old versions bungeecord? If so, I can try to make bungeeforge for it.

Probably not worth it... 👍
