### ISSUE TITLE
Please add support for Forge 1.20.2

### ISSUE THREAD

**Issue by SimonMage** [caunt/BungeeForge#14]
Please could you add BungeeForge for 1.20.2 ?

**Comment by SimonMage** [comment]
Here the error in console spammed and the mod doesn't work;
https://mcpaste.io/2957d4f3c64b6e7b

**Comment by caunt** [comment]
Hi 👋 of course, I'll release update in the nearest days

**Comment by caunt** [comment]
Just released [v1.0.6](https://github.com/caunt/BungeeForge/releases/tag/v1.0.6) with 1.20.2 build, should work with newer minor versions as well.
