### ISSUE TITLE
1.7.10 Support

### ISSUE THREAD

**Issue by superhealing** [caunt/BungeeForge#2]
Hello, i know 1.7.10 may sound super ancient but mostly new modpacks will not able to run with crucible or anything else. There is heavy  improvements on 1.7.10 space, especially GTNH Dev's managed to port java 8 to 20 already, and some mods straight not compatible with crucible/thermos. 
For testing purposes you can try [The Lost Era Modpack](https://www.curseforge.com/minecraft/modpacks/the-lost-era-modpack) since that modpack doesn't not support thermos/crucible or any other forks.
Thank you for reading.

**Comment by caunt** [comment]
Hello! I know there is still community playing with 1.7.10 modpacks, so its fine to support that version. I've released 1.7.10 version and tested it with The Lost Era Modpack. Appreciate for your feedback if it works well for you. [Release](https://github.com/caunt/BungeeForge/releases/tag/v1.0.5)

**Comment by superhealing** [comment]
> Hello! I know there is still community playing with 1.7.10 modpacks, so its fine to support that version. I've released 1.7.10 version and tested it with The Lost Era Modpack. Appreciate for your feedback if it works well for you. [Release](https://github.com/caunt/BungeeForge/releases/tag/v1.0.5)

Works, i got no issues :). take my 🍰
