### ISSUE TITLE
Please reconnect

### ISSUE THREAD

**Issue by elory5** [caunt/BungeeForge#20]
Hello, I have a problem with connecting to the server. Whenever I connect Im getting "Please reconnect" and in the mods server "[18:37:12] [Server thread/INFO] [minecraft/ServerLoginPacketListenerImpl]: com.mojang.authlib.GameProfile@23edc5da[id=d8c1be24-f8c6-3213-8188-7e795ad591c0,name=elory5,properties={},legacy=false] (/192.168.2.10:0) lost connection: Disconnected"

I have forge 1.20.1-47.2.18
Ambassador plugin Ambassador-Velocity-1.4.4-all.jar
bungeeforge-1.20.1.jar

**Comment by p0t4t0sandwich** [comment]
That's just how Ambassador works. Reconnect and you'll be in the Forge server.
If you want to change that behavior, install the Forward Forge Client Reset Packet mod on the client.
