### ISSUE TITLE
1.20

### ISSUE THREAD

**Issue by chrgargar4** [caunt/BungeeForge#3]
Is there any plan to release it for 1.20?

Thanks.

**Comment by caunt** [comment]
Hello, do you need exactly 1.20? I plan to skip ahead it and release 1.20.1

**Comment by chrgargar4** [comment]
Not really, 1.20.1 is fine. is there any approximate release date? 🤔

**Comment by caunt** [comment]
I'ill release it in 1-2 days

**Comment by caunt** [comment]
[Released](https://github.com/caunt/BungeeForge/releases/tag/v1.0.5) 1.20.1 version but should also work with all 1.20 minor versions. Let me know if it works for you well, because I have not much time to test it.
