### ISSUE TITLE
Error connecting to server

### ISSUE THREAD

**Issue by chrgargar4** [caunt/BungeeForge#5]
Hi! Im trying to use your mod on 1.20.1, I followed readme but still facing this console error: 

![image](https://github.com/caunt/BungeeForge/assets/65631716/8f40c756-e98e-47ab-9517-0e81b8397ed8)

If I remove bungeeforge I can connect with no issues.

Do u know what can be the problem? Thanks 😄

**Comment by caunt** [comment]
Please provide full log
