### ISSUE TITLE
Forwarding doesn't seem to work quite right

### ISSUE THREAD

**Issue by LurgenAU** [caunt/BungeeForge#6]
I've got BungeeForge working behind Velocity with Ambassador installed, but I'm getting the wrong UUID on the back-end server almost as if forwarding isn't working quite right. Other servers behind the same proxy get their player forwarding data correctly - is there somewhere I can configure online-mode or similar for BungeeForge?

I'm running this on Magma 1.18.2.

**Comment by caunt** [comment]
BungeeForge does nothing to forwarded data. Probably the problem somewhere behind the proxy or in Velocity itself. Maybe you can provide steps to reproduce issue so I can help you with debugging.

**Comment by wolflord212312** [comment]
> BungeeForge does nothing to forwarded data. Probably the problem somewhere behind the proxy or in Velocity itself. Maybe you can provide steps to reproduce issue so I can help you with debugging.

Nah they will never respond might as well close it and magma supports modern forwarding directly now and it already supported bungee directly so honestly is a skill issue on his part

**Comment by LurgenAU** [comment]
> Nah they will never respond might as well close it and magma supports modern forwarding directly now and it already supported bungee directly so honestly is a skill issue on his part

I hadn't responded because I hadn't found the time to document a process to reproduce the issue. Particularly since I ditched Magma due to quite a few bugs in the thing.

There's no need to be a jerk though, since you pretty obviously don't actually understand the issue at hand here.
