### ISSUE TITLE
1.20.1 Offline UUID's

### ISSUE THREAD

**Issue by ADevito-Spiro** [caunt/BungeeForge#7]
When using Ambassador, Proxy-Compatible Forge, and Bungeeforge to connect two servers, one 1.20.1 and one 1.12.2. The 1.12.2 server  gets the correct UUID, while the 1.20.1 server gets an offline UUID, which makes the users skin to not appear and permissions to get screwed up. Removing pcf from the 1.20.1 server has no effect except for the command stuff that they handle.

**Comment by caunt** [comment]
BungeeForge does nothing to forwarded data. Probably some misconfiguration going there. Can you explain your setup to reproduce the issue?
