### ISSUE TITLE
Fresh install of Forge 1.12.2-14.23.5.2860 won't start with BF

### ISSUE THREAD

**Issue by p0t4t0sandwich** [caunt/BungeeForge#8]
Just been testing the proxy compatibility with all the different Forge hybrids and other methods, and I can't seem to get it to run.
No other mods running, starts fine without BF.
Re-installed Forge 1.12.2 and tested all previous versions of BF 1.12.2 to be sure, all with the same result. Please let me know if I'm missing something, or if I can make any tweaks to how I'm running things.
Server log: [latest.log](https://github.com/caunt/BungeeForge/files/12842223/latest.log)

After further testing it seems like it's the same deal for 1.7.10

**Comment by wolflord212312** [comment]
https://www.curseforge.com/minecraft/mc-mods/unimixins

Unimixins fixes the 1.7.10 issue

**Comment by p0t4t0sandwich** [comment]
That fixed it yep, and [Mixin Booter](https://www.curseforge.com/minecraft/mc-mods/mixin-booter) got 1.12.2 up and running
